steps:

  - name: 'gcr.io/cloud-builders/gradle'
    dir: 'api/'
    args: ['build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'api/Dockerfile', '--tag=eu.gcr.io/$PROJECT_ID/cupkey', 'api/.']

  # - id: build-cupkey-api
  #   name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-f', 'api/Dockerfile', '-t', 'eu.gcr.io/starthack2019-234023/cupkey', 'api/.']
  #   timeout: 600s
  #   # images: ['eu.gcr.io/starthack2019-234023/cupkey']

  - id: deploy-mysql
    name: mysql
    args: ['--detach']
    timeout: 180s
    env:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=Ys0nf1wg
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root

images: ['eu.gcr.io/$PROJECT_ID/cupkey']