steps:

  - name: 'gcr.io/cloud-builders/gradle'
    dir: 'api/'
    args: ['build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'api/Dockerfile', '--tag=eu.gcr.io/$PROJECT_ID/cupkey', 'api/.']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
      - 'apply'
      - '-f'
      - 'k8s/mysql.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=starthack2019'

  - id: deploy-mysql
    name: mysql
    args: ['--detach']
    timeout: 180s
    env:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=Ys0nf1wg
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root

images: ['eu.gcr.io/$PROJECT_ID/cupkey']