steps:

  # api
  - id: gradle-build-cupkey-api
    name: 'gcr.io/cloud-builders/gradle'
    dir: 'api/'
    args: ['build']
  - id: docker-build-cupkey-api
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'api/Dockerfile', '--tag=eu.gcr.io/$PROJECT_ID/cupkey-api:$SHORT_SHA', 'api/.']
  - id: docker-move-cupkey-api-latest-tag
    name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'eu.gcr.io/$PROJECT_ID/cupkey-api:$SHORT_SHA', 'eu.gcr.io/$PROJECT_ID/cupkey-api:latest']

  # return machine / sbb hq
  - id: docker-build-return-machine
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'return_machine/Dockerfile', '--tag=eu.gcr.io/$PROJECT_ID/cupkey-return:$SHORT_SHA', 'return_machine/.']
  - id: docker-move-cupkey-return-latest-tag
    name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'eu.gcr.io/$PROJECT_ID/cupkey-return:$SHORT_SHA', 'eu.gcr.io/$PROJECT_ID/cupkey-return:latest']

  # deploy mysql as api backend
  - id: deploy-mysql
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/mysql.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=starthack2019'

  # # deploy traefik rbac and so on
  # - id: deploy-traefik-adds
  #   name: 'gcr.io/cloud-builders/kubectl'
  #   args:
  #     - 'apply'
  #     - '-f'
  #     - 'k8s/traefik_adds.yaml'
  #   env:
  #     - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-c'
  #     - 'CLOUDSDK_CONTAINER_CLUSTER=starthack2019'

  # deploy traefik
  - id: deploy-traefik-ingress
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/traefik.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=starthack2019'

  # deploy cupkey-api
  - id: deploy-cupkey-api
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/cupkey.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=starthack2019'

  # deploy cupkey-return
  - id: deploy-cupkey-return
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/return_machine.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=starthack2019'

images: ['eu.gcr.io/$PROJECT_ID/cupkey-api:latest', 'eu.gcr.io/$PROJECT_ID/cupkey-return:latest']