steps:

  - id: gradle-build-cupkey-api
    name: 'gcr.io/cloud-builders/gradle'
    dir: 'api/'
    args: ['build']
  - id: docker-build-cupkey-api
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'api/Dockerfile', '--tag=eu.gcr.io/$PROJECT_ID/cupkey-api:$COMMIT_SHA', 'api/.']
  - id: docker-move-latest-tag
    name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'eu.gcr.io/$PROJECT_ID/cupkey-api:$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/cupkey-api:latest']

  - id: docker-build-return-machine
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'return_machine/Dockerfile', '--tag=eu.gcr.io/$PROJECT_ID/cupkey-return:$COMMIT_SHA', 'return_machine/.']
  - id: docker-move-latest-tag
    name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'eu.gcr.io/$PROJECT_ID/cupkey-return:$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/cupkey-return:latest']

  - id: deploy-mysql
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/mysql.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=starthack2019'

  - id: deploy-cupkey-api
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/cupkey.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=starthack2019'

images: ['eu.gcr.io/$PROJECT_ID/cupkey']