version: "3.0"

services:

  cupkey:
    image: benleb/cupkey:latest
    container_name: "cupkey"
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"

  mysql:
    image: mysql
    container_name: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=Ys0nf1wg
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root