package cup;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;


@RestController    // This means that this class is a Controller
@RequestMapping(path="/v1") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private CupRepository cupRepository;
	

	@GetMapping(path="/cups")
	public @ResponseBody Iterable<Cup> getAll() {
		// This returns a JSON or XML with the users
		return cupRepository.findAll();
	}

	@PostMapping(value="/cups")
	public Cup create(@RequestBody Cup cup){
		return cupRepository.save(cup);
	}
}


