apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cupkey-api
  name: cupkey-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cupkey-api
    spec:
      containers:
        - name: web
          image: gcr.io/$PROJECT_ID/cupkey-api:latest
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080