apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cupkey-api
  labels:
spec:
  rules:
  - host: api-cupkey.benleb.de
    http:
      paths:
      - path: /*
        backend:
          serviceName: cupkey-api-service
          servicePort: 80