apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cupkey-return
  labels:
    app: cupkey-return
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cupkey-return
    spec:
      containers:
        - name: cupkey-return
          image: eu.gcr.io/starthack2019-234023/cupkey-return:latest
          ports:
          - containerPort: 5000
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: cupkey-return-service
spec:
  selector:
    app: cupkey-return
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  tls.key: very
  tls.crt: very
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cupkey-return
  labels:
    app: cupkey-return
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
    - secretName: cupkey-return-tls-cert
  rules:
  - host: return-cupkey.benleb.de
    http:
      paths:
      - path: /
        backend:
          serviceName: cupkey-return-service
          servicePort: 5000