---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  labels:
    app: traefik-ingress
spec:
  selector:
    app: traefik-ingress
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-admin
  labels:
    app: traefik-ingress
spec:
  selector:
    app: traefik-ingress
  ports:
    - port: 8080
      name: webui
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
        address = ":443"
      [entryPoints.https.tls]
    #[acme]
    #email = "lefevre.kevin@gmail.com"
    #storageFile = "/acme/acme.json"
    #entryPoint = "https"
    #onDemand = true
    #onHostRule = true
    #caServer = "https://acme-staging.api.letsencrypt.org/directory"
    #[[acme.domains]]
    #main = "archifleks.net"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  labels:
    app: traefik-ingress
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: traefik-ingress
        name: traefik-ingress
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-conf
        - name: acme
          hostPath:
            path: /srv/configs/acme/acme.json
      containers:
        - image: containous/traefik
          name: traefik-ingress
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              name: "config"
            - mountPath: "/acme/acme.json"
              name: "acme"
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
            - containerPort: 8080
          args:
            - --configfile=/config/traefik.toml
            - --web
            - --kubernetes
            - --logLevel=DEBUG